
variables:
    vGITLAB_TOKEN: "${GITLAB_TOKEN}"
    vXY_TOKEN: "${XY_TOKEN}"


stages:          # List of stages for jobs, and their order of execution .
  - BuildStage
  - XygeniScan
  #- test
  #- deploy


Xygeni-job:
  stage: XygeniScan
  #image: ubuntu@sha256:55e5613c8c7bcd8044aaf09d64d20518964a0d7a6e41af129f95b731301c2659
  image: maven:3-jdk-11
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

  script:
    - |
      #!/bin/bash
      declare -a repo_list=(
                          "https://gitlab.com/xygroup1/xy-onboarding.git"
                          "https://gitlab.com/xygroup1/gl_cicd_top10_1.git"
                          )

      chmod +x ./scan_repo_list.sh           
      ./scan_repo_list.sh -d . -x $vXY_TOKEN -c gitlab -p $vGITLAB_TOKEN -z "${repo_list[*]}"

  #needs: ["build-job"]
    #- cat ./scanner/conf/misconfigurations/unprotected_branch.yml
    #- ./scanner/xygeni util conf-update
    #- cat ./scanner/conf/misconfigurations/unprotected_branch.yml

push-build-job:       # This job runs in the build stage, which runs first.
  stage: BuildStage
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - echo "Building the code (main)..."
    - echo "Build complete."


mr-build-job:       # This job runs in the build stage, which runs first.
  stage: BuildStage
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "Building the code (pr)..."
    - echo "Build complete."





