trigger:
- main

pool:
  vmImage: ubuntu-latest


variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Security
  variables:
    - name: System.Debug
      value: false
    - group: PRO
    - name: vXY_TOKEN
      value: $[variables.XY_TOKEN]
    - name: vAZURE_TOKEN
      value: $[variables.AZURE_TOKEN]
  jobs:
  - job: "Xy_Scanner_on_PUSH"
    steps:
    
    - checkout: self
      fetchDepth: 0
    
    - task: CmdLine@2
      displayName: 'Install and run xygeni scanner'
      inputs:
        script: |
            #!/bin/bash

            declare -a repo_list=(
                          "https://luisgarciaxygeni@dev.azure.com/luisgarciaxygeni/XyDemoPPE/_git/XyDemoPPE"
                          "https://luisgarciaxygeni@dev.azure.com/luisgarciaxygeni/ADO-cicd_top10_1/_git/ADO-cicd_top10_1"
                          )

            chmod +x $(Build.SourcesDirectory)/scan_repo_list.sh           
            $(Build.SourcesDirectory)/scan_repo_list.sh -d $(Build.SourcesDirectory) -x $(vXY_TOKEN) -c azure_devops -p $(vAZURE_TOKEN) -z "${repo_list[*]}"


    
