trigger:
- main

pool:
  vmImage: ubuntu-latest


variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Security
  variables:
    - name: System.Debug
      value: false
    - group: PRO
    - name: vXY_TOKEN
      value: $[variables.XY_TOKEN]
    - name: vAZURE_TOKEN
      value: $[variables.AZURE_TOKEN]
  jobs:
  - job: "Xy_Scanner_on_PUSH"
    steps:
    
    - checkout: self
      fetchDepth: 10
    
    - task: Bash@3
      displayName: 'Show vars '
      inputs:
        targetType: 'inline'
        script: |
            ls -l
            java -version
            whoami
            pwd 
            echo $(vXY_TOKEN)
            echo $(vAZURE_TOKEN)


    - script: |
        echo $(vAZURE_TOKEN)
        env
        env | grep xxAZURE_TOKEN
      workingDirectory: $(workingDirectory)
      displayName: 'XXXXX'
      env:
        xxAZURE_TOKEN: $(vAZURE_TOKEN)


    - task: CmdLine@2
      displayName: 'Install and run xygeni scanner'
      env:
        xxAZURE_TOKEN: $(vAZURE_TOKEN)
      inputs:
        script: |
            #!/bin/bash

            declare -a repo_list=(
                          "https://github.com/lgvorg1/secrets_local.git"
                          "https://github.com/lgvorg1/cicd_top10_1.git"
                          )

            chmod +x $(Build.SourcesDirectory)/scan_repo_list.sh           
            $(Build.SourcesDirectory)/scan_repo_list.sh -d $(Build.SourcesDirectory) -x $(vXY_TOKEN) -c azure_devops -p $(vAZURE_TOKEN) -z "${repo_list[*]}"


    
