# This is a basic workflow to help you get started with Actions 

name: Xygeni CI/CD Security Scan

# Controls when the workflow will run
on:
  push: 
    branches: [ "main" ]
  # Triggers the workflow on pull request events for the "main" branch
  pull_request_target: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab sd 
  workflow_dispatch:
    # 15 3 * * 1-5
    # every weekday morning at 3:15 am
    #In the POSIX locale, the user or application shall ensure that a crontab entry is a text file consisting of lines of six fields each. The fields shall be separated by <blank> characters. The first five fields shall be integer patterns that specify the following:
    #Minute [0,59]
    #Hour [0,23]
    #Day of the month [1,31]
    #Month of the year [1,12]
    #Day of the week ([0,6] with 0=Sunday)

 
env:
  XY_TOKEN: ${{ secrets.XY_TOKEN_PRO }}


jobs:
  # This workflow contains a single job called "xygeni_security_scan"
  xygeni_cicd_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # ref: "refs/pull/${{ github.event.number }}/merge"
    # ref: ${{ github.event.pull_request.head.sha }}
  
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out main code
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags..
          # Default: 1
          fetch-depth: '0'


      # Runs a set of commands using the runners shell   
      - name: Scan repo list 
        run: |
          #!/bin/bash

          declare -a repo_list=(
                          "https://github.com/lgvorg1/secrets_local.git"
                          "https://github.com/lgvorg1/cicd_top10_1.git"
                          )

          chmod +x ${GITHUB_WORKSPACE}/scan_repo_list.sh           
          ${GITHUB_WORKSPACE}/scan_repo_list.sh -d ${GITHUB_WORKSPACE} -x $XY_TOKEN -c github -p ${{ secrets.GH_PAT }} -z "${repo_list[*]}"


